import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Figtree } from "next/font/google";
import { KoHo } from "next/font/google";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const figtree = Figtree({
  subsets: ["latin"],
  variable: "--font-figtree", // this
});

const koho = KoHo({
  subsets: ["latin"],
  variable: "--font-koho", // this
  weight: ["200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${figtree.variable} ${koho.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
